export const COMPLAINT_CATEGORY = Object.freeze({
  IT: "IT",
  HR: "HR",
  FACILITY: "FACILITY",
  FINANCE: "FINANCE",
  OTHER: "OTHER",
});

export const COMPLAINT_CATEGORIES = Object.freeze([
  COMPLAINT_CATEGORY.IT,
  COMPLAINT_CATEGORY.HR,
  COMPLAINT_CATEGORY.FACILITY,
  COMPLAINT_CATEGORY.FINANCE,
  COMPLAINT_CATEGORY.OTHER,
]);